- name: Download wordpress
  get_url:
    url: "{{ wordrpess_url }}"
    dest: /tmp/wordpress.tar.gz

- name: Unarchive worpdress
  unarchive:
    src: "{{ destination }}"
    dest: /tmp
    remote_src: yes
    creates: /tmp/wordpress


- name: Template a file to /etc/files.conf
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php


- name: Copy file with owner and permissions
  copy:
    src: "/tmp/wordpress/."
    dest: /var/www/html
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'
    remote_src: yes

- name: Restart httpd
  service:
    name: "{{ package_name }}"
    state: restarted