- name: Download wordpress
  get_url:
    url: "{{ wordpress_url }}"
    dest: /tmp/wordpress.tar.gz

- name: Unarchive worpdress
  unarchive:
    src: "{{ folder }}"
    dest: /tmp
    remote_src: yes
    creates: /tmp/wordpress

- name: Template a file to /var/www/html
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php

- name: Copy file with owner and permissions
  copy:
    src: "/tmp/wordpress/."
    dest: /var/www/html
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0755'
    remote_src: yes



- name: Restart httpd
  service:
    name: httpd
    state: restarted