- name: Install mariadb
  yum:
    name:
      - mariadb
      - mariadb-server

- name: Enable mariadb
  service:
    name: mariadb
    state: started
    enabled: yes

  # - name: Check database
  #   shell: mysql -e "use wordpress;"
  #   register: database_exists
  #   ignore_errors: true

  # - name: Check user
  #   shell: mysql -e "SELECT USER FROM mysql.user WHERE user='kaizen'"
  #   register: check_user
  #   ignore_errors: true

- name: create database
  shell: mysql -e "CREATE DATABASE {{ db_name }};"
    #when: database_exists.rc !=0

  # - name: create user
  #   shell: mysql -e "CREATE USER 'kaizen'@'localhost' IDENTIFIED BY 'kaizen123';"
  #   when: check_user.rc !=0


- name: grant permission
  shell: mysql -e "GRANT ALL PRIVILEGES ON {{ db_name }}.* TO '{{ db_user }}'@'localhost' IDENTIFIED BY '{{ db_password }}';"

- name: flush privileges
  shell: mysql -e "FLUSH PRIVILEGES;"
    
- name: Set SELinux to permissive
  selinux:
    policy: targeted
    state: permissive